spring:
    profiles:
        active: local

server:
    servlet:
        context-path: /api
    port: 8888
--- 
spring:
    config:
        activate:
            on-profile: local
--- 
spring:
    config:
        activate:
            on-profile: dev
--- 
spring:
    config:
        activate:
            on-profile: prod

